server:
  servlet:
    context-path: /ems

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?serverTimezone=UTC&userUnicode=true&characterEncoding=UTF-8
    username: root
    password: 11235813
  resources:
    static-locations: classpath:/templates/,classpath:/static/

mybatis:
  mapper-locations: classpath:/com/promethuesYuan/mapper/*.xml
  type-aliases-package: com.promethuesYuan.entity
